// <auto-generated />
using System;
using Freito.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Freito.Infrastructure.Migrations
{
    [DbContext(typeof(FreitoDbContext))]
    [Migration("20260923092606_InitialDataFoundation")]
    partial class InitialDataFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Freito.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("AfterJson")
                        .HasColumnType("json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("json");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId", "ChangedAt");

                    b.HasIndex("Entity", "EntityId", "ChangedAt");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Freito.Domain.Entities.CargoType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDangerous")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsProhibited")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("cargo_types", (string)null);
                });

            modelBuilder.Entity("Freito.Domain.Entities.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("carriers", (string)null);
                });

            modelBuilder.Entity("Freito.Domain.Entities.Currency", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<int>("DecimalDigits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Code");

                    b.ToTable("currencies", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "USD",
                            DecimalDigits = 2,
                            Name = "US Dollar"
                        },
                        new
                        {
                            Code = "THB",
                            DecimalDigits = 2,
                            Name = "Thai Baht"
                        },
                        new
                        {
                            Code = "EUR",
                            DecimalDigits = 2,
                            Name = "Euro"
                        });
                });

            modelBuilder.Entity("Freito.Domain.Entities.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("RateToBase")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode", "EffectiveDate")
                        .IsUnique();

                    b.ToTable("exchange_rates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrencyCode = "USD",
                            EffectiveDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RateToBase = 1m
                        });
                });

            modelBuilder.Entity("Freito.Domain.Entities.FreightRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarrierId")
                        .HasColumnType("int");

                    b.Property<string>("ContainerSize")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<int>("DestinationPortId")
                        .HasColumnType("int");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<int>("OriginPortId")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceMax")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PriceMin")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("WeightBreakMax")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<decimal?>("WeightBreakMin")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("DestinationPortId");

                    b.HasIndex("OriginPortId", "DestinationPortId", "Mode", "Direction", "IsActive", "ValidFrom", "ValidTo");

                    b.ToTable("freight_rates", (string)null);
                });

            modelBuilder.Entity("Freito.Domain.Entities.Incoterm", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RiskTransferPoint")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("varchar(240)");

                    b.Property<bool>("SellerPaysFreight")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Code");

                    b.ToTable("incoterms", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "EXW",
                            Name = "Ex Works",
                            RiskTransferPoint = "Seller's named premises; goods placed at the buyer's disposal, not loaded.",
                            SellerPaysFreight = false
                        },
                        new
                        {
                            Code = "FCA",
                            Name = "Free Carrier",
                            RiskTransferPoint = "Named place after delivery to the buyer-nominated carrier.",
                            SellerPaysFreight = false
                        },
                        new
                        {
                            Code = "FAS",
                            Name = "Free Alongside Ship",
                            RiskTransferPoint = "Alongside the vessel at the named port of shipment.",
                            SellerPaysFreight = false
                        },
                        new
                        {
                            Code = "FOB",
                            Name = "Free on Board",
                            RiskTransferPoint = "On board the vessel at the named port of shipment.",
                            SellerPaysFreight = false
                        },
                        new
                        {
                            Code = "CFR",
                            Name = "Cost and Freight",
                            RiskTransferPoint = "On board the vessel at the port of shipment.",
                            SellerPaysFreight = true
                        },
                        new
                        {
                            Code = "CIF",
                            Name = "Cost, Insurance and Freight",
                            RiskTransferPoint = "On board the vessel at the port of shipment.",
                            SellerPaysFreight = true
                        },
                        new
                        {
                            Code = "CPT",
                            Name = "Carriage Paid To",
                            RiskTransferPoint = "When the goods are handed over to the seller-contracted carrier.",
                            SellerPaysFreight = true
                        },
                        new
                        {
                            Code = "CIP",
                            Name = "Carriage and Insurance Paid To",
                            RiskTransferPoint = "When the goods are handed over to the seller-contracted carrier.",
                            SellerPaysFreight = true
                        },
                        new
                        {
                            Code = "DPU",
                            Name = "Delivered at Place Unloaded",
                            RiskTransferPoint = "At the named destination after the goods have been unloaded.",
                            SellerPaysFreight = true
                        },
                        new
                        {
                            Code = "DAP",
                            Name = "Delivered at Place",
                            RiskTransferPoint = "At the named destination, ready for unloading.",
                            SellerPaysFreight = true
                        },
                        new
                        {
                            Code = "DDP",
                            Name = "Delivered Duty Paid",
                            RiskTransferPoint = "At the named destination, cleared for import and ready for unloading.",
                            SellerPaysFreight = true
                        });
                });

            modelBuilder.Entity("Freito.Domain.Entities.IncotermChargeRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChargeSide")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("IncotermCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Payer")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("IncotermCode", "ChargeSide")
                        .IsUnique();

                    b.ToTable("incoterm_charge_rules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChargeSide = "Origin",
                            IncotermCode = "EXW",
                            Payer = "Buyer"
                        },
                        new
                        {
                            Id = 2,
                            ChargeSide = "Destination",
                            IncotermCode = "EXW",
                            Payer = "Buyer"
                        },
                        new
                        {
                            Id = 3,
                            ChargeSide = "Origin",
                            IncotermCode = "FCA",
                            Payer = "Seller"
                        },
                        new
                        {
                            Id = 4,
                            ChargeSide = "Destination",
                            IncotermCode = "FCA",
                            Payer = "Buyer"
                        },
                        new
                        {
                            Id = 5,
                            ChargeSide = "Origin",
                            IncotermCode = "FAS",
                            Payer = "Seller"
                        },
                        new
                        {
                            Id = 6,
                            ChargeSide = "Destination",
                            IncotermCode = "FAS",
                            Payer = "Buyer"
                        },
                        new
                        {
                            Id = 7,
                            ChargeSide = "Origin",
                            IncotermCode = "FOB",
                            Payer = "Seller"
                        },
                        new
                        {
                            Id = 8,
                            ChargeSide = "Destination",
                            IncotermCode = "FOB",
                            Payer = "Buyer"
                        },
                        new
                        {
                            Id = 9,
                            ChargeSide = "Origin",
                            IncotermCode = "CFR",
                            Payer = "Seller"
                        },
                        new
                        {
                            Id = 10,
                            ChargeSide = "Destination",
                            IncotermCode = "CFR",
                            Payer = "Buyer"
                        },
                        new
                        {
                            Id = 11,
                            ChargeSide = "Origin",
                            IncotermCode = "CIF",
                            Payer = "Seller"
                        },
                        new
                        {
                            Id = 12,
                            ChargeSide = "Destination",
                            IncotermCode = "CIF",
                            Payer = "Buyer"
                        },
                        new
                        {
                            Id = 13,
                            ChargeSide = "Origin",
                            IncotermCode = "CPT",
                            Payer = "Seller"
                        },
                        new
                        {
                            Id = 14,
                            ChargeSide = "Destination",
                            IncotermCode = "CPT",
                            Payer = "Buyer"
                        },
                        new
                        {
                            Id = 15,
                            ChargeSide = "Origin",
                            IncotermCode = "CIP",
                            Payer = "Seller"
                        },
                        new
                        {
                            Id = 16,
                            ChargeSide = "Destination",
                            IncotermCode = "CIP",
                            Payer = "Buyer"
                        },
                        new
                        {
                            Id = 17,
                            ChargeSide = "Origin",
                            IncotermCode = "DPU",
                            Payer = "Seller"
                        },
                        new
                        {
                            Id = 18,
                            ChargeSide = "Destination",
                            IncotermCode = "DPU",
                            Payer = "Seller"
                        },
                        new
                        {
                            Id = 19,
                            ChargeSide = "Origin",
                            IncotermCode = "DAP",
                            Payer = "Seller"
                        },
                        new
                        {
                            Id = 20,
                            ChargeSide = "Destination",
                            IncotermCode = "DAP",
                            Payer = "Seller"
                        },
                        new
                        {
                            Id = 21,
                            ChargeSide = "Origin",
                            IncotermCode = "DDP",
                            Payer = "Seller"
                        },
                        new
                        {
                            Id = 22,
                            ChargeSide = "Destination",
                            IncotermCode = "DDP",
                            Payer = "Seller"
                        });
                });

            modelBuilder.Entity("Freito.Domain.Entities.LocalCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountMax")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("AmountMin")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CalcBasis")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("ChargeSide")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("ChargeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<decimal?>("MinimumCharge")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<int>("PortId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChargeType");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("PortId", "Direction", "Mode", "ChargeSide", "CalcBasis", "ChargeType", "CurrencyCode")
                        .IsUnique();

                    b.ToTable("local_charges", (string)null);
                });

            modelBuilder.Entity("Freito.Domain.Entities.Port", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Type", "Country", "City");

                    b.ToTable("ports", (string)null);
                });

            modelBuilder.Entity("Freito.Domain.Entities.Quotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("CargoTypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Cbm")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<string>("ContainerSize")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerCompany")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("DestinationPortId")
                        .HasColumnType("int");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("FinalPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FreightCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FxRateUsed")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("IncotermCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<decimal>("LocalChargeTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<int>("OriginPortId")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("QuoteNo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("RateSource")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("ReadyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("CargoTypeId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DestinationPortId");

                    b.HasIndex("IncotermCode");

                    b.HasIndex("OriginPortId");

                    b.HasIndex("QuoteCurrency");

                    b.HasIndex("QuoteNo")
                        .IsUnique();

                    b.HasIndex("ReadyDate");

                    b.HasIndex("Status", "CreatedByUserId");

                    b.ToTable("quotations", (string)null);
                });

            modelBuilder.Entity("Freito.Domain.Entities.QuotationLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Basis")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Qty")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<int>("QuotationId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceLocalChargeId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceRateId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId");

                    b.HasIndex("SourceLocalChargeId");

                    b.HasIndex("SourceRateId");

                    b.ToTable("quotation_lines", (string)null);
                });

            modelBuilder.Entity("Freito.Domain.Entities.QuotationStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("QuotationId")
                        .HasColumnType("int");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("varchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("QuotationId", "At");

                    b.ToTable("quotation_status_history", (string)null);
                });

            modelBuilder.Entity("Freito.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Freito.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Freito.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Freito.Domain.Entities.ExchangeRate", b =>
                {
                    b.HasOne("Freito.Domain.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Freito.Domain.Entities.FreightRate", b =>
                {
                    b.HasOne("Freito.Domain.Entities.Carrier", null)
                        .WithMany()
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Freito.Domain.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Freito.Domain.Entities.Port", null)
                        .WithMany()
                        .HasForeignKey("DestinationPortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Freito.Domain.Entities.Port", null)
                        .WithMany()
                        .HasForeignKey("OriginPortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Freito.Domain.Entities.IncotermChargeRule", b =>
                {
                    b.HasOne("Freito.Domain.Entities.Incoterm", null)
                        .WithMany()
                        .HasForeignKey("IncotermCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Freito.Domain.Entities.LocalCharge", b =>
                {
                    b.HasOne("Freito.Domain.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("CurrencyCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Freito.Domain.Entities.Port", null)
                        .WithMany()
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Freito.Domain.Entities.Quotation", b =>
                {
                    b.HasOne("Freito.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Freito.Domain.Entities.CargoType", null)
                        .WithMany()
                        .HasForeignKey("CargoTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Freito.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Freito.Domain.Entities.Port", null)
                        .WithMany()
                        .HasForeignKey("DestinationPortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Freito.Domain.Entities.Incoterm", null)
                        .WithMany()
                        .HasForeignKey("IncotermCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Freito.Domain.Entities.Port", null)
                        .WithMany()
                        .HasForeignKey("OriginPortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Freito.Domain.Entities.Currency", null)
                        .WithMany()
                        .HasForeignKey("QuoteCurrency")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Freito.Domain.Entities.QuotationLine", b =>
                {
                    b.HasOne("Freito.Domain.Entities.Quotation", null)
                        .WithMany()
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Freito.Domain.Entities.LocalCharge", null)
                        .WithMany()
                        .HasForeignKey("SourceLocalChargeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Freito.Domain.Entities.FreightRate", null)
                        .WithMany()
                        .HasForeignKey("SourceRateId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Freito.Domain.Entities.QuotationStatusHistory", b =>
                {
                    b.HasOne("Freito.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Freito.Domain.Entities.Quotation", null)
                        .WithMany()
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
